from __future__ import annotations

from pathlib import Path
from typing import Protocol

from app.schemas import CaptureModel


class CaptureRepository(Protocol):
    def init(self) -> None: ...
    def create(self, **kwargs) -> CaptureModel: ...
    def update(self, capture_id: str, **updates) -> CaptureModel | None: ...
    def get(self, capture_id: str) -> CaptureModel | None: ...
    def list(self, limit: int = 50) -> list[CaptureModel]: ...
    def list_pending_ids(self) -> list[str]: ...
    def find_by_url(self, url: str, *, statuses: tuple[str, ...] = ("done", "processing", "queued")) -> CaptureModel | None: ...
    def find_by_source_identity(self, platform: str, source_item_id: str, *, statuses: tuple[str, ...] = ("done", "processing", "queued")) -> CaptureModel | None: ...
    def clear_completed(self) -> int: ...
    def delete(self, capture_id: str) -> bool: ...


class ArtifactRepository(Protocol):
    def capture_workspace(self, capture_id: str) -> Path: ...


class JobRepository(Protocol):
    def enqueue(self, capture_id: str) -> None: ...
    def pending(self) -> list[str]: ...
